#################### default parameters ################################
# favicon module: https://github.com/gethugothemes/hugo-modules/tree/master/images#favicon-implementation
favicon = "images/favicon.png"
# logo module: https://github.com/gethugothemes/hugo-modules/tree/master/images#logo-implementation
logo = "images/logo.png"
logo_darkmode = "images/logo-darkmode.png"
# use `px` or `x` with logo_width, example: "100px".
# Note: logo_width is not work with .svg file
logo_width = "150px"
logo_height = "32px"
# if logo_webp set false, will not generate WEBP version of logo | default is true
logo_webp = true
# logo text will only show when logo is missing.
logo_text = "Qoherent"
# navbar fixed to top
navbar_fixed = true
# theme-mode
theme_switcher = false#true
theme_default = "dark" # available options [light/dark/system]
# Main Sections
mainSections = ["blog"]
# contact form action
contact_form_action = "https://formspree.io/f/xayrneza"
# google tag manager, see https://developers.google.com/tag-manager/
google_tag_manager = "" # example: G-XXXXXXXXXX
# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>"
custom_script = ""
# copyright 
copyright = "© Qoherent 2024. Let's build intelligent radios together."

# Navigation button
[navigation_button]
enable = true
label = "Contact"
link = "contact/"

# seo meta data for OpenGraph / Twitter Card
# seo module: https://github.com/gethugothemes/hugo-modules/tree/master/seo-tools/basic-seo
[metadata]
keywords = ["SDR", "Intelligent Radio"]
description = "Qoherent - accelerating the pace of intelligent radios."
author = "Qoherent.Inc"
image = "images/waterfall2-drawn.jpg"
# image = "images/og-image.png"


# site verifications
# verification module: https://github.com/gethugothemes/hugo-modules/tree/master/seo-tools/site-verifications
[site_verification]
google = ""   # Your verification code
bing = ""     # Your verification code
baidu = ""    # Your verification code
facebook = "" # Your verification code
mastodon = "" # Your verification code

# cookies
[cookies]
enable = true
expire_days = 60
content = "This site uses cookies. Please see privacy policy."
button = "Got it"
